-- Auto-generated by Apocalypse Footnotes build pipeline. DO NOT EDIT DIRECTLY.
local items = {
    ["10gal_hat"] = "cph_full_art_a8ce6684e006b3e4db578108",
}

local variants = {
}

return {
    items = items,
    variants = variants,
}
